name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage
          python -m pip install --upgrade -r requirements.txt
      - name: generate coverage report
        run: |
          coverage run --source=beehyve --omit=beehyve/__version__.py -m behave
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: behave
          verbose: true
