name: isort

on: [push, pull_request]

jobs:
  imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade isort
          python -m pip install -e .
      - name: check import sorting
        run: |
          isort -c --profile black .
