name: Lint
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
      - name: flake8
        run: |
          flake8 .
      - name: bandit
        run: |
          bandit -c bandit.yml -r .
      - name: mypy
        run: |
          mypy beehyve